[package]
name = "flame_effects"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.6"
error-iter = "0.4"
log = "0.4"
winit = "0.29"
winit_input_helper = "0.16.0"
pixels = "0.15"
colorsys = { version = "*", default-features = false }
rand = "0.9.0"